# Generated by Django 5.1.4 on 2025-08-26 14:10

from django.core.management import call_command, CommandError
from django.db import migrations

def load_fixture(apps, schema_editor):
    try:
        call_command('loaddata', 'tags', verbosity=0)  # 拡張子なし
    except CommandError as e:
        print(f'⚠️ Skipping "tags" fixture: {e}')

class Migration(migrations.Migration):
    dependencies = [('terms', '0001_initial')]
    operations = [migrations.RunPython(load_fixture, migrations.RunPython.noop)]