# Generated by Django 5.1.4 on 2025-08-26 14:10

from django.core.management import call_command
from django.db import migrations

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'app/fixture/tags.json', app_label='app')

class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
