services:
  django:
    build:
      context: .
      dockerfile: infra/docker/django/Dockerfile.prod
    container_name: django_app
    env_file:
      - .env.prod
    expose:
      - "8000"
    restart: always
    networks:
      - app_network


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/iterms/staticfiles
      - ./infra/docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
    restart: always
    networks:
      - app_network
    profiles: ["production"]

networks:
  app_network:
    driver: bridge

volumes:
  static_volume: