# Generated by Django 5.2.4 on 2025-08-25 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='用語集名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開/非公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vocabularies', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vocabularies.vocabulary', verbose_name='用語集')),
            ],
            options={
                'unique_together': {('user', 'vocabulary')},
            },
        ),
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='補足・メモ')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_entries', to='terms.term', verbose_name='用語')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_terms', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='vocabularies.vocabulary', verbose_name='用語集')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('vocabulary', 'term')},
            },
        ),
    ]
