# Generated by Django 5.2.4 on 2025-08-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_entries', to='terms.term', verbose_name='用語'),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
