# --- ビルドステージ ---
FROM python:3.13 AS builder

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    libmariadb-dev-compat \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /iterms

COPY ./requirements.txt ./

RUN pip install --upgrade pip && pip wheel --no-cache-dir --wheel-dir=/wheels -r requirements.txt

COPY ./app ./app

# --- 本番ステージ ---
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    libmariadb3 \
    default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /iterms

RUN pip install --upgrade pip

# ビルドステージからwheelディレクトリをコピー
COPY --from=builder /wheels /wheels
COPY --from=builder /iterms/app/. ./app/

COPY ./requirements.txt ./

RUN pip install --no-cache-dir --no-index --find-links=/wheels -r requirements.txt

EXPOSE 8000

CMD ["sh", "-c", "cd app && python manage.py migrate && python manage.py collectstatic --noinput　--settings=config.settings.prod && gunicorn core.wsgi:application --bind 0.0.0.0:8000"]