FROM python:3.13

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 必要パッケージのインストール
RUN apt-get update && apt-get install -y \
    build-essential \
    libmariadb-dev-compat \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /iterms

# 依存関係インストール
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# wait-for-it.sh をダウンロードして実行可能に
RUN curl -o /wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
    && chmod +x /wait-for-it.sh

EXPOSE 8000